# -*- coding: utf-8 -*-
"""Agente1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOXiekGUY-sG5yCyTqu9j-O3y_9Cyyrb

# **Agente con LangChain que consulta documentos de una carpeta (RAG “lite”)**
El principal objetivo es entender qué es un agente (LLM + herramientas) y ver cómo “decide” qué herramienta usar para responder con evidencia.

# Agente = LLM + Tools + Reglas.





*   El LLM “razona” qué necesita.

*   Las tools son funciones que hacen cosas reales (leer archivos, buscar texto…).


*   El system prompt marca límites (“solo usar docs de la carpeta”).
"""

#INSTALACIÓN

!pip -q install langchain langchain-openai langchain-community

import requests
requests.__version__

"""# Configurar OpenRouter (API gratuita)

Has creado una API key en OpenRouter.

Ahora la pegamos en una variable de entorno.

Probamos una llamada simple para comprobar que todo funciona antes de montar el agente.
"""

import os
from langchain_openai import ChatOpenAI

# 1) Pegamos la API key de OpenRouter //Es única y cuidado con mostrarla!
os.environ["OPENAI_API_KEY"] = "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"

# 2) Creamos el LLM apuntando a OpenRouter
llm = ChatOpenAI(
    model="openrouter/free",                 # router de modelos gratuitos
    base_url="https://openrouter.ai/api/v1", # endpoint OpenRouter
    temperature=0,
    default_headers={
        "HTTP-Referer": "https://colab.research.google.com",
        "X-OpenRouter-Title": "Demo LangChain Agents (Colab)",
    },
)

# 3) Hacemos una llamada de prueba a modo demo
resp = llm.invoke("Dime en una frase qué es un agente en IA.")
print(resp.content)

"""
# Preparar la carpeta de documentos

Un agente necesita “mundo real” con el que interactuar.
Aquí haremos una carpeta /content/docs con textos de ejemplo sobre animales."""

from pathlib import Path

BASE_PATH = Path("/content/docs")
BASE_PATH.mkdir(parents=True, exist_ok=True)

doc1 = """# Axolote
El axolote (Ambystoma mexicanum) es un anfibio neoténico.
Habita en cuerpos de agua dulce, especialmente en Xochimilco (México).
Dato curioso: puede regenerar extremidades y partes del sistema nervioso.

# Orca
La orca (Orcinus orca) es un mamífero marino.
Vive en océanos de todo el mundo y es un depredador ápice.
"""

doc2 = """# Pulpo común
El pulpo común (Octopus vulgaris) es un cefalópodo.
Es conocido por su inteligencia y capacidad de camuflaje.

# Preguntas frecuentes
- ¿Son los pulpos vertebrados? No, son invertebrados.
"""

(BASE_PATH / "animales_1.md").write_text(doc1, encoding="utf-8")
(BASE_PATH / "animales_2.md").write_text(doc2, encoding="utf-8")

print("Carpeta:", BASE_PATH)
print("Archivos:", [p.name for p in BASE_PATH.iterdir()])

"""# Definir las herramientas (tools)

Las tools son las “manos” del agente.
El LLM no puede leer tu disco por sí solo: necesita funciones.

Tools que creamos para esta demo:



*   list_files(path) --> lista archivos disponibles
*   read_text_file(filepath) --> lee un archivo

*   keyword_search(query, path) --> busca una palabra/frase en todos los docs








"""

from typing import List
from langchain_core.tools import tool

@tool
def list_files(path: str) -> List[str]:
    """Lista archivos .txt/.md dentro de una carpeta."""
    p = Path(path)
    if not p.exists() or not p.is_dir():
        return [f"[ERROR] Folder not found: {path}"]

    files = []
    for fp in sorted(p.rglob("*")):
        if fp.is_file() and fp.suffix.lower() in [".txt", ".md"]:
            files.append(str(fp))
    return files[:200]

@tool
def read_text_file(filepath: str) -> str:
    """Lee un .txt/.md y devuelve su contenido (recortado)."""
    fp = Path(filepath)
    if not fp.exists() or not fp.is_file():
        return f"[ERROR] File not found: {filepath}"
    if fp.suffix.lower() not in [".txt", ".md"]:
        return f"[ERROR] Unsupported file type: {fp.suffix}"

    content = fp.read_text(encoding="utf-8", errors="ignore")
    return content[:12000]

@tool
def keyword_search(query: str, path: str) -> str:
    """Busca una palabra/frase en todos los .txt/.md y devuelve snippets con nombre de archivo."""
    p = Path(path)
    if not p.exists() or not p.is_dir():
        return f"[ERROR] Folder not found: {path}"

    hits = []
    q = query.lower()

    for fp in sorted(p.rglob("*")):
        if fp.is_file() and fp.suffix.lower() in [".txt", ".md"]:
            text = fp.read_text(encoding="utf-8", errors="ignore")
            t = text.lower()
            if q in t:
                idx = t.find(q)
                start = max(0, idx - 150)
                end = min(len(text), idx + 150)
                snippet = text[start:end].replace("\n", " ")
                hits.append(f"- {fp.name}: ...{snippet}...")

        if len(hits) >= 10:
            break

    return "\n".join(hits) if hits else "No matches."

"""
# Crear el “agente” (LLM + tools + reglas)

El system prompt define el comportamiento:



1.  usa tools antes de responder
2.  cita archivos
3. si no encuentras, dilo, no inventes






"""

import json, re
from langchain_core.messages import SystemMessage, HumanMessage, ToolMessage

# ============================================================================
# 1) Preparamos un "mapa" nombre_tool -> objeto_tool
#    Esto nos permite ejecutar una herramienta por su nombre (string).
# ============================================================================
tool_map = {t.name: t for t in tools}  # tools = [list_files, read_text_file, keyword_search]

# ============================================================================
# 2) "Enlazamos" el LLM con las tools.
#    Esto NO ejecuta herramientas todavía.
#    Simplemente le dice al modelo: "estas son las herramientas disponibles"
#    para que pueda decidir llamar a una de ellas.
# ============================================================================
agent_model = llm.bind_tools(tools)

# ============================================================================
# 3) System prompt: reglas del "agente"
#    - El modelo debe usar herramientas para buscar evidencia
#    - Debe citar el archivo
#    - No debe inventar
# ============================================================================
system_text = f"""
Eres un agente que responde usando SOLO documentos de la carpeta: {BASE_PATH}
Reglas:
- Antes de responder, usa herramientas para buscar evidencia.
- Cita el/los nombres de archivo usados.
- Si no encuentras evidencia en los docs, dilo claramente.
- No inventes datos no presentes en los documentos.
"""

def ask(question: str, max_steps: int = 6, verbose: bool = True) -> str:
    """
    Esta función implementa un agente "a mano" (tool loop):
    - Enviamos la pregunta al modelo.
    - Si el modelo pide usar una herramienta, la ejecutamos.
    - Le devolvemos al modelo el resultado de esa herramienta.
    - Repetimos hasta que el modelo dé una respuesta final.

    max_steps evita bucles infinitos si el modelo se queda pidiendo tools sin parar.
    verbose imprime cada paso (útil para demo en clase).
    """

    # =========================================================================
    # 4) Construimos el historial de mensajes (chat)
    #    - SystemMessage: las reglas del agente
    #    - HumanMessage: la pregunta del usuario
    # =========================================================================
    messages = [
        SystemMessage(content=system_text),
        HumanMessage(content=question),
    ]

    # =========================================================================
    # 5) Bucle de "razonar --> usar tool --> razonar"
    #    Cada iteración es un "paso" del agente.
    # =========================================================================
    for step in range(1, max_steps + 1):

        # ---------------------------------------------------------------------
        # 5.1) Llamada al modelo con el historial actual
        #      El modelo puede:
        #        A) Pedir usar una herramienta (tool call)
        #        B) Responder directamente (respuesta final)
        #        C) (a veces) devolver el tool call en texto en vez de estructura
        # ---------------------------------------------------------------------
        resp = agent_model.invoke(messages)

        # =========================================================================
        # CASO A (el mejor): El modelo devuelve tool calls en formato estructurado
        # resp.tool_calls == [
        #   {"name": "keyword_search", "args": {...}, "id": "...", ...}
        # ]
        # =========================================================================
        tool_calls = getattr(resp, "tool_calls", None) or []
        if tool_calls:
            if verbose:
                print(f"[STEP {step}] tool_calls estructurados:", tool_calls)

            # IMPORTANTE:
            # Añadimos el mensaje del "assistant" que contiene la petición de tools.
            # Esto mantiene el historial coherente para la siguiente llamada.
            messages.append(resp)

            # Puede pedir 1 o varias tools en el mismo paso.
            for tc in tool_calls:
                # Nombre de la herramienta y argumentos (diccionario)
                name = tc["name"]
                args = tc.get("args", {}) or {}

                if verbose:
                    print(f"[STEP {step}] Ejecutando tool: {name} args={args}")

                # Ejecutamos la herramienta real en Python
                tool = tool_map.get(name)
                result = tool.invoke(args) if tool else f"[ERROR] Tool desconocida: {name}"

                # Devolvemos el resultado al modelo en un ToolMessage.
                # tool_call_id relaciona este resultado con la llamada concreta.
                messages.append(
                    ToolMessage(content=str(result), tool_call_id=tc["id"])
                )

            # Volvemos al inicio del bucle:
            # ahora el modelo verá el resultado de la tool y podrá responder o pedir otra tool.
            continue

        # =========================================================================
        # CASO B (fallback): Algunos modelos (o routers) devuelven la llamada a tool
        # dentro del texto, por ejemplo:
        #   "TOOLCALL>[{...}]CALL>"
        #
        # Esto ocurre a veces con OpenRouter/free, porque el modelo real puede variar.
        # =========================================================================
        text = (getattr(resp, "content", "") or "").strip()

        if "TOOLCALL>" in text:
            if verbose:
                print(f"[STEP {step}] Toolcall en texto detectado:\n{text}")

            # Extraemos el JSON incrustado entre "TOOLCALL>" y "CALL>"
            m = re.search(r"TOOLCALL>\s*(\[\{.*?\}\])\s*CALL>", text, flags=re.DOTALL)
            if not m:
                # Si no podemos parsearlo, devolvemos el texto tal cual para debug
                return text

            calls = json.loads(m.group(1))

            # Añadimos el mensaje del assistant que contiene el toolcall textual
            messages.append(resp)

            for c in calls:
                name = c.get("name")
                args = c.get("arguments", {}) or {}

                if verbose:
                    print(f"[STEP {step}] Ejecutando tool: {name} args={args}")

                tool = tool_map.get(name)
                result = tool.invoke(args) if tool else f"[ERROR] Tool desconocida: {name}"

                # Aquí NO tenemos tool_call_id fiable (porque viene en texto),
                # así que metemos el resultado como mensaje humano "RESULTADO_TOOL ...".
                # (Es un truco para que el modelo reciba la info igualmente.)
                messages.append(HumanMessage(content=f"RESULTADO_TOOL {name}: {result}"))

            # Volvemos al bucle para que el modelo use el resultado y responda.
            continue

        # =========================================================================
        # CASO C: Respuesta final normal
        # Si no hay tool_calls estructurados y tampoco hay TOOLCALL textual,
        # interpretamos que el modelo ya ha respondido.
        # =========================================================================
        if verbose:
            print(f"[STEP {step}] Respuesta final.")
        return text

    # =========================================================================
    # Si llegamos aquí es porque el modelo no dio respuesta final en max_steps
    # =========================================================================
    return "[ERROR] max_steps alcanzado sin respuesta final."

#NO EJECUTAR, SIMPLEMENTE EJEMPLO DEL ERROR DADO

#QUE DEVUELVE
TOOLCALL>[{"name": "keyword_search", "arguments": {"query": "Xochimilco", "path": "/content/docs"}}CALL>


#QUE DEBERÍA CON TOOL CALLING
resp.tool_calls == [
    {
        "name": "keyword_search",
        "args": {
            "query": "Xochimilco",
            "path": "/content/docs"
        },
        "id": "xyz123",
        "type": "tool_call"
    }
]

"""# Preguntas de demo

listar archivos

1.   buscar keyword
2.   respuesta con evidencia
3. pregunta trampa








"""

resp = ask(f"Lista los archivos disponibles en {BASE_PATH}.")
print(resp)

resp = ask("Busca 'Xochimilco' en los documentos y dime en qué archivo aparece.")
print(resp)

resp = ask("¿Qué dice el documento sobre el axolote? Responde en 4 bullets y cita el archivo.")
print(resp)

resp = ask("¿Cuántos años vive un axolote normalmente? Dame una cifra exacta.")
print(resp)

resp = llm.invoke("Cuanto vive un axolote exactamente?")
print(resp.content)